# syntax version of docker compose, NOT the version of docker
version: "3.9"

services:
  web:
    build: . # uses the current directory's dockerfile image
    ports: 
      # binds the container and the host machine to the exposed port
      # uses the default Flask port 5000
      - "5000:5000" 
  redis:
    image: "redis:alpine" # pulled from docker hub registry